version: '3'
services:
  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"
    networks:
      - mynetwork
    volumes:
      - redis-data:/data

  node:
    build:
      context: .
      dockerfile: dockerfiles/node.Dockerfile
    container_name: node-container
    ports:
      - "3000:3000"
    depends_on:
      - redis
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
volumes:
  redis-data: